### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by mhilbert** [fsesterh/THK_Tst_ManualScoring_Question#4]
PHP Warning:  The use statement with non-compound name 'ilDBInterface' has no effect in /data_nfs/htdocs/devel8x/Modules/TestQuestionPool/Setup/class.ilFixMissingQuestionDuplicationMigration.php on line 23

Environment: ILIAS 8.8, PHP 8.0.30, TstManualScoringQuestion 8.0.0

**Comment by fsesterh** [comment]
Please provide the steps to reproduce this error message. Does this happen when running composer?

**Comment by mhilbert** [comment]
Yes, when running the Composer from ILIAS root directory.

But, sorry, I re-checked all steps I did and realized now that the warning occured already before installing your plugin.
